#!/bin/bash

set -e

docker build --rm \
  --tag ccc-media-dev \
  --build-arg RUBY_VERSION="$(cat .rbenv-version)"  \
  --build-arg UID=$(id -u) \
  config/tools/devimage

set -x
# Inside the container, do 'bundle exec rails server -b 0.0.0.0'
exec docker run -it --rm \
  -p 3344:3000 \
  -v $(pwd):/work \
  -w /work \
  -u $(id -u) \
  ccc-media-dev \
  /bin/bash -l
